/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author User
 */
public class TelaAdicionarProduto extends javax.swing.JDialog {

    /**
     * Creates new form TelaAdicionarProduto
     */
    public TelaAdicionarProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelImagemDivisoriaHorizontal = new javax.swing.JLabel();
        labelAdicionarProduto = new javax.swing.JLabel();
        labelDescricaoProduto = new javax.swing.JLabel();
        textFieldDescricaoProduto = new javax.swing.JTextField();
        buttonCancelar = new javax.swing.JButton();
        buttonAdicionar = new javax.swing.JButton();
        labelImagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelImagemDivisoriaHorizontal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/divisoria-horizontal-tela-opcoes.png"))); // NOI18N
        getContentPane().add(labelImagemDivisoriaHorizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 1));

        labelAdicionarProduto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelAdicionarProduto.setText("<html><center>Adicionar um produto na <strong>LISTA DE<br/>PRODUTOS EM ESTOQUE</strong></center></html>");
        getContentPane().add(labelAdicionarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 11, -1, -1));

        labelDescricaoProduto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelDescricaoProduto.setText("Descrição do produto");
        getContentPane().add(labelDescricaoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, -1, -1));

        textFieldDescricaoProduto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(textFieldDescricaoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 380, -1));

        buttonCancelar.setBackground(new java.awt.Color(204, 0, 0));
        buttonCancelar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        buttonCancelar.setText("Cancelar");
        getContentPane().add(buttonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 168, -1, -1));

        buttonAdicionar.setBackground(new java.awt.Color(0, 153, 0));
        buttonAdicionar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        buttonAdicionar.setText("Adicionar");
        getContentPane().add(buttonAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 168, -1, -1));

        labelImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/fundo-tela-opcoes.png"))); // NOI18N
        getContentPane().add(labelImagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaAdicionarProduto dialog = new TelaAdicionarProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionar;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JLabel labelAdicionarProduto;
    private javax.swing.JLabel labelDescricaoProduto;
    private javax.swing.JLabel labelImagemDivisoriaHorizontal;
    private javax.swing.JLabel labelImagemFundo;
    private javax.swing.JTextField textFieldDescricaoProduto;
    // End of variables declaration//GEN-END:variables
}
