/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author User
 */
public class TelaRemoverProduto extends javax.swing.JDialog {

    /**
     * Creates new form TelaRemoverProduto
     */
    public TelaRemoverProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelImagemDivisoriaHorizontal = new javax.swing.JLabel();
        labelProdutoSelecionado = new javax.swing.JLabel();
        labelRemoverProduto = new javax.swing.JLabel();
        buttonNao = new javax.swing.JButton();
        buttonSim = new javax.swing.JButton();
        labelImagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelImagemDivisoriaHorizontal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/divisoria-horizontal-tela-opcoes.png"))); // NOI18N
        getContentPane().add(labelImagemDivisoriaHorizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 1));

        labelProdutoSelecionado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelProdutoSelecionado.setText("Produto que está selecionado:");
        getContentPane().add(labelProdutoSelecionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        labelRemoverProduto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelRemoverProduto.setText("<html><center>Deseja realmente remover este produto da<br/><strong>LISTA DE PRODUTOS EM ESTOQUE</strong>?</center></html>");
        getContentPane().add(labelRemoverProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 108, -1, -1));

        buttonNao.setBackground(new java.awt.Color(204, 0, 0));
        buttonNao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonNao.setForeground(new java.awt.Color(255, 255, 255));
        buttonNao.setText("Não");
        getContentPane().add(buttonNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 162, -1, -1));

        buttonSim.setBackground(new java.awt.Color(0, 153, 0));
        buttonSim.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonSim.setForeground(new java.awt.Color(255, 255, 255));
        buttonSim.setText("Sim");
        getContentPane().add(buttonSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 162, -1, -1));

        labelImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/fundo-tela-opcoes.png"))); // NOI18N
        getContentPane().add(labelImagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRemoverProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRemoverProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRemoverProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRemoverProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaRemoverProduto dialog = new TelaRemoverProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNao;
    private javax.swing.JButton buttonSim;
    private javax.swing.JLabel labelImagemDivisoriaHorizontal;
    private javax.swing.JLabel labelImagemFundo;
    private javax.swing.JLabel labelProdutoSelecionado;
    private javax.swing.JLabel labelRemoverProduto;
    // End of variables declaration//GEN-END:variables
}
