/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author User
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneListaDeProdutosEmEstoque = new javax.swing.JScrollPane();
        listListaDeProdutosEmEstoque = new javax.swing.JList<>();
        labelListaDeProdutosEmEstoque = new javax.swing.JLabel();
        labelMensagemContainerOcultador = new javax.swing.JLabel();
        labelImagemContainerOcultador = new javax.swing.JLabel();
        labelProdutoSelecionado = new javax.swing.JLabel();
        labelIconeRemoverProduto = new javax.swing.JLabel();
        labelRemoverProduto = new javax.swing.JLabel();
        labelImagemContainerBrancoRemoverProduto = new javax.swing.JLabel();
        labelImagemContainerCinzaRemoverProduto = new javax.swing.JLabel();
        labelImagemDivisoriaHorizontal = new javax.swing.JLabel();
        labelImagemDivisoriaHorizontalMenor = new javax.swing.JLabel();
        labelImagemDivisoriaVertical = new javax.swing.JLabel();
        labelIconeAdicionarProduto = new javax.swing.JLabel();
        labelAdicionarProduto = new javax.swing.JLabel();
        labelImagemContainerBrancoAdicionarProduto = new javax.swing.JLabel();
        labelImagemContainerCinzaAdicionarProduto = new javax.swing.JLabel();
        labelQuantidadeDeProdutosRegistrados = new javax.swing.JLabel();
        labelImagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista de Produtos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollPaneListaDeProdutosEmEstoque.setViewportView(listListaDeProdutosEmEstoque);

        getContentPane().add(scrollPaneListaDeProdutosEmEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 43, 374, 182));

        labelListaDeProdutosEmEstoque.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelListaDeProdutosEmEstoque.setText("<html><strong>LISTA DE PRODUTOS EM ESTOQUE</strong></html>");
        getContentPane().add(labelListaDeProdutosEmEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 11, -1, -1));

        labelMensagemContainerOcultador.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelMensagemContainerOcultador.setText("<html><center>Ao selecionar um produto da <strong>LISTA DE<br/>PRODUTOS EM ESTOQUE</strong>, você irá se<br/>deparar com a opção de removê-lo da<br/>referida lista.</center></html>");
        getContentPane().add(labelMensagemContainerOcultador, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 119, -1, -1));

        labelImagemContainerOcultador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/container-ocultador.png"))); // NOI18N
        getContentPane().add(labelImagemContainerOcultador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, 361, 124));

        labelProdutoSelecionado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelProdutoSelecionado.setText("<html>Produto que está selecionado:</html>");
        getContentPane().add(labelProdutoSelecionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, -1, -1));

        labelIconeRemoverProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icones/remover-produto.png"))); // NOI18N
        getContentPane().add(labelIconeRemoverProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 165, 50, 50));

        labelRemoverProduto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelRemoverProduto.setText("<html>Remover este produto da <strong>LISTA<br/>DE PRODUTOS EM ESTOQUE</strong></html>");
        getContentPane().add(labelRemoverProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 168, -1, -1));

        labelImagemContainerBrancoRemoverProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/container-branco.png"))); // NOI18N
        getContentPane().add(labelImagemContainerBrancoRemoverProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 155, 361, 70));

        labelImagemContainerCinzaRemoverProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/container-cinza.png"))); // NOI18N
        getContentPane().add(labelImagemContainerCinzaRemoverProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 155, 361, 70));

        labelImagemDivisoriaHorizontal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/divisoria-horizontal.png"))); // NOI18N
        getContentPane().add(labelImagemDivisoriaHorizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 1));

        labelImagemDivisoriaHorizontalMenor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/divisoria-horizontal-menor.png"))); // NOI18N
        getContentPane().add(labelImagemDivisoriaHorizontalMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 91, 361, 1));

        labelImagemDivisoriaVertical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/divisoria-vertical.png"))); // NOI18N
        getContentPane().add(labelImagemDivisoriaVertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 0, 1, 705));

        labelIconeAdicionarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icones/adicionar-produto.png"))); // NOI18N
        getContentPane().add(labelIconeAdicionarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 21, 50, 50));

        labelAdicionarProduto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelAdicionarProduto.setText("<html>Adicionar um produto na <strong>LISTA DE<br/>PRODUTOS EM ESTOQUE</strong></html>");
        getContentPane().add(labelAdicionarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 24, -1, -1));

        labelImagemContainerBrancoAdicionarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/container-branco.png"))); // NOI18N
        getContentPane().add(labelImagemContainerBrancoAdicionarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 361, 70));

        labelImagemContainerCinzaAdicionarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/container-cinza.png"))); // NOI18N
        getContentPane().add(labelImagemContainerCinzaAdicionarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 361, 70));

        labelQuantidadeDeProdutosRegistrados.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelQuantidadeDeProdutosRegistrados.setText("Quantidade de produtos registrados: 0");
        getContentPane().add(labelQuantidadeDeProdutosRegistrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 235, -1, -1));

        labelImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/fundo-tela-principal.png"))); // NOI18N
        labelImagemFundo.setToolTipText("");
        getContentPane().add(labelImagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 705));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAdicionarProduto;
    private javax.swing.JLabel labelIconeAdicionarProduto;
    private javax.swing.JLabel labelIconeRemoverProduto;
    private javax.swing.JLabel labelImagemContainerBrancoAdicionarProduto;
    private javax.swing.JLabel labelImagemContainerBrancoRemoverProduto;
    private javax.swing.JLabel labelImagemContainerCinzaAdicionarProduto;
    private javax.swing.JLabel labelImagemContainerCinzaRemoverProduto;
    private javax.swing.JLabel labelImagemContainerOcultador;
    private javax.swing.JLabel labelImagemDivisoriaHorizontal;
    private javax.swing.JLabel labelImagemDivisoriaHorizontalMenor;
    private javax.swing.JLabel labelImagemDivisoriaVertical;
    private javax.swing.JLabel labelImagemFundo;
    private javax.swing.JLabel labelListaDeProdutosEmEstoque;
    private javax.swing.JLabel labelMensagemContainerOcultador;
    private javax.swing.JLabel labelProdutoSelecionado;
    private javax.swing.JLabel labelQuantidadeDeProdutosRegistrados;
    private javax.swing.JLabel labelRemoverProduto;
    private javax.swing.JList<String> listListaDeProdutosEmEstoque;
    private javax.swing.JScrollPane scrollPaneListaDeProdutosEmEstoque;
    // End of variables declaration//GEN-END:variables
}
